//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../../polarshell/polarshell/backend/models/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "terminal:exit": $$createType0,
        "terminal:output": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = models$0.TerminalExitPayload.createFrom;
const $$createType1 = models$0.TerminalOutputPayload.createFrom;

configure();
