// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    "defaultShell": string;
    "fontFamily": string;
    "fontSize": number;
    "scrollback": number;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("defaultShell" in $$source)) {
            this["defaultShell"] = "";
        }
        if (!("fontFamily" in $$source)) {
            this["fontFamily"] = "";
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("scrollback" in $$source)) {
            this["scrollback"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class SessionInfo {
    "id": string;
    "shell": string;
    "cols": number;
    "rows": number;
    "active": boolean;

    /** Creates a new SessionInfo instance. */
    constructor($$source: Partial<SessionInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("shell" in $$source)) {
            this["shell"] = "";
        }
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("active" in $$source)) {
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInfo($$parsedSource as Partial<SessionInfo>);
    }
}

export class ShellProfile {
    "id": string;
    "name": string;
    "command": string;
    "available": boolean;

    /** Creates a new ShellProfile instance. */
    constructor($$source: Partial<ShellProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShellProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ShellProfile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShellProfile($$parsedSource as Partial<ShellProfile>);
    }
}

export class TerminalExitPayload {
    "sessionId": string;
    "exitCode": number;

    /** Creates a new TerminalExitPayload instance. */
    constructor($$source: Partial<TerminalExitPayload> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("exitCode" in $$source)) {
            this["exitCode"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalExitPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalExitPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalExitPayload($$parsedSource as Partial<TerminalExitPayload>);
    }
}

export class TerminalOutputPayload {
    "sessionId": string;
    "data": string;

    /** Creates a new TerminalOutputPayload instance. */
    constructor($$source: Partial<TerminalOutputPayload> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalOutputPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalOutputPayload {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalOutputPayload($$parsedSource as Partial<TerminalOutputPayload>);
    }
}
