// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "./backend/models/models.js";

export function CloseSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3305403653, sessionID);
}

export function CreateSession(shellID: string, cols: number, rows: number): $CancellablePromise<models$0.SessionInfo> {
    return $Call.ByID(2914743863, shellID, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetSession(sessionID: string): $CancellablePromise<models$0.SessionInfo> {
    return $Call.ByID(1764697881, sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListShells(): $CancellablePromise<models$0.ShellProfile[]> {
    return $Call.ByID(2555996722).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LoadSettings(): $CancellablePromise<models$0.AppSettings> {
    return $Call.ByID(621118204).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Resize(sessionID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByID(270758441, sessionID, cols, rows);
}

export function SaveSettings(appSettings: models$0.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(1937264445, appSettings);
}

export function Write(sessionID: string, data: string): $CancellablePromise<void> {
    return $Call.ByID(371925220, sessionID, data);
}

// Private type creation functions
const $$createType0 = models$0.SessionInfo.createFrom;
const $$createType1 = models$0.ShellProfile.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = models$0.AppSettings.createFrom;
